CREATE TABLE "chat-ui_account" (
	"accessToken" text,
	"accessTokenExpiresAt" timestamp,
	"accountId" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"id" text PRIMARY KEY NOT NULL,
	"idToken" text,
	"password" text,
	"providerId" text NOT NULL,
	"refreshToken" text,
	"refreshTokenExpiresAt" timestamp,
	"scope" text,
	"updatedAt" timestamp with time zone,
	"userId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat-ui_conversation" (
	"id" text PRIMARY KEY NOT NULL,
	"title" varchar(255) NOT NULL,
	"model" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"userId" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "chat-ui_message" (
	"id" text PRIMARY KEY NOT NULL,
	"conversationId" text NOT NULL,
	"role" text NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"pinned" boolean,
	"reactions" json,
	"error" text
);
--> statement-breakpoint
CREATE TABLE "chat-ui_model" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "chat-ui_post" (
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "chat-ui_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "chat-ui_session" (
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"id" text PRIMARY KEY NOT NULL,
	"ipAddress" text,
	"token" text NOT NULL,
	"updatedAt" timestamp with time zone,
	"userAgent" text,
	"userId" text NOT NULL,
	CONSTRAINT "chat-ui_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "chat-ui_user" (
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"email" text NOT NULL,
	"emailVerified" boolean NOT NULL,
	"id" text PRIMARY KEY NOT NULL,
	"image" text,
	"name" text NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "chat-ui_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "chat-ui_verification" (
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"expiresAt" timestamp NOT NULL,
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"updatedAt" timestamp with time zone,
	"value" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "chat-ui_account" ADD CONSTRAINT "chat-ui_account_userId_chat-ui_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."chat-ui_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat-ui_conversation" ADD CONSTRAINT "chat-ui_conversation_userId_chat-ui_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."chat-ui_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat-ui_message" ADD CONSTRAINT "chat-ui_message_conversationId_chat-ui_conversation_id_fk" FOREIGN KEY ("conversationId") REFERENCES "public"."chat-ui_conversation"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "chat-ui_session" ADD CONSTRAINT "chat-ui_session_userId_chat-ui_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."chat-ui_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_userId_idx" ON "chat-ui_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "post_name_idx" ON "chat-ui_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_userId_idx" ON "chat-ui_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "user_name_idx" ON "chat-ui_user" USING btree ("name");--> statement-breakpoint
CREATE INDEX "user_email_idx" ON "chat-ui_user" USING btree ("email");--> statement-breakpoint
CREATE INDEX "verification_identifier_idx" ON "chat-ui_verification" USING btree ("identifier");