import type { Metadata } from "next"
import { Geist, Geist_Mono, Noto_Sans } from "next/font/google"

import { ThemeProvider } from "@/components/theme-provider"
import { SidebarProvider } from "@/components/ui/sidebar"
import { TooltipProvider } from "@/components/ui/tooltip"
import { TRPCReactProvider } from "@/lib/api/client"
import { cn } from "@/lib/utils"

import "@/styles/globals.css"

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
})

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
})

export const metadata: Metadata = {
  description: "Generated by create lx2 app",
  title: "Create Lx2 App",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "anitialiased font-sans",
          geistSans.variable,
          geistMono.variable,
          notoSans.variable,
        )}
        style={
          {
            "--header-height": "calc(var(--spacing) * 16)",
            "--sidebar-width": "calc(var(--spacing) * 74)",
          } as React.CSSProperties
        }
      >
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            disableTransitionOnChange
            enableSystem
          >
            <TooltipProvider>
              <SidebarProvider>{children}</SidebarProvider>
            </TooltipProvider>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
